### ISSUE TITLE
Running Alto fails with java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so`

### ISSUE THREAD

**Issue by megodoonch** [coli-saar/alto#82]
I downloaded the jar file of the most recent version, but when I try to open it, I get an error:

```
(base) mego@trinket:~/IdeaProjects/alto$ java -jar ~/Downloads/alto-2.3.6-all.jar 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2651)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at java.desktop/java.awt.Component.<clinit>(Component.java:621)
	at de.up.ling.irtg.main.Alto.main(Alto.java:28)
```

It looks to me like it can't find my Java, so I checked for it:

```
(base) mego@trinket:~/IdeaProjects/alto$ java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
(base) mego@trinket:~/IdeaProjects/alto$ which java
/usr/bin/java
```

But when I follow the exact path in the error, indeed there is no such file as `libawt_xawt.so`.

```
(base) mego@trinket:~/IdeaProjects/alto$ ls /usr/lib/jvm/
java-1.11.0-openjdk-amd64/        .java-1.11.0-openjdk-amd64.jinfo  java-11-openjdk-amd64/            
(base) mego@trinket:~/IdeaProjects/alto$ ls /usr/lib/jvm/java-11-openjdk-amd64/
bin  conf  docs  legal  lib  man  release
```

Is this a me problem? I can't tell. If it's relevant, I also can't build it myself: gradle complains about docfile problems.

**Comment by alexanderkoller** [comment]
Hi Meaghan, it would surprise me if the bug were in alto-2.3.6 - people in various places have recently used Alto without encountering it. That doesn't mean it couldn't be an Alto problem anyway, of course.

Could this be the problem you're encountering? https://stackoverflow.com/questions/67391845/exception-java-lang-unsatisfiedlinkerror-when-trying-to-open-allure-reports-in-w

**Comment by megodoonch** [comment]
Oh Hallelulia, you fxed it! Thank you, my google-fu clearly came up short today.
